// CANONICAL EXAMPLE — Lead Reply Tools
// Use this as the template for tools.ts in new automations.
// File: lib/automations/lead-reply/tools.ts

/**
 * Lead Reply — Tools
 *
 * Deterministic TypeScript functions that do the actual work.
 * No AI calls here — just pure I/O: send emails, post to APIs, etc.
 *
 * Key principles:
 * - Pure functions, no shared state
 * - One function per side-effect
 * - All secrets come from env vars, never from config
 * - Throw on hard failure; return `null` on soft failure (logged upstream)
 */

import { Resend } from "resend";

export interface SendReplyParams {
  /** Recipient email address */
  to: string;
  /** Recipient name (for personalization) */
  toName: string;
  /** Sender email — must be a verified Resend domain */
  fromEmail: string;
  /** Display name for the From field */
  fromName: string;
  /** The reply subject line */
  subject: string;
  /** Full reply text generated by Claude */
  body: string;
  /** Optional reply-to address (if different from fromEmail) */
  replyTo?: string;
}

/**
 * Sends the AI-generated reply via Resend.
 *
 * Returns the Resend message ID on success, throws on failure.
 * The caller (index.ts) is responsible for logging the result.
 */
export async function sendReply(params: SendReplyParams): Promise<string> {
  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) {
    throw new Error("RESEND_API_KEY is not set");
  }

  const resend = new Resend(apiKey);

  const { data, error } = await resend.emails.send({
    from: `${params.fromName} <${params.fromEmail}>`,
    to: `${params.toName} <${params.to}>`,
    subject: params.subject,
    text: params.body,
    ...(params.replyTo ? { reply_to: params.replyTo } : {}),
  });

  if (error) {
    throw new Error(`Resend delivery failed: ${error.message}`);
  }

  return data?.id ?? "unknown";
}

// ── How to add more tools ──────────────────────────────────────────────────
//
// For a Social Poster automation, you'd add:
//
//   export async function postToFacebook(params: {
//     pageId: string;
//     message: string;
//     imageUrl?: string;
//   }): Promise<string> { ... }
//
// For a Review Collector, you'd add:
//
//   export async function sendReviewRequest(params: {
//     to: string;
//     customerName: string;
//     businessName: string;
//     reviewUrl: string;
//   }): Promise<string> { ... }
//
// ── Pattern rules ──────────────────────────────────────────────────────────
// 1. Each function does ONE thing
// 2. All return the external ID or confirmation string (for logging)
// 3. Throw Error on failure — never return null silently
// 4. Never read config directly — caller passes what's needed
// 5. Never import from the automation's own index.ts or workflow.ts
